import React, { FC, ReactNode } from "react";
import Head from "next/head";

type LayoutProps = {
  title: string;
  children: ReactNode;
};

export const Layout: FC<LayoutProps> = (props) => {
  const { title = "T3 Stack", children } = props;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-auto container flex min-h-screen flex-col items-center justify-center p-4">
        {children}
      </main>
    </>
  );
};
